# Generated by Django 3.2.16 on 2024-02-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240206_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_add',
        ),
    ]
